name: smart_query_assistant

services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile.postgres
    container_name: sqa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U demo"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      postgres
      -c shared_preload_libraries='age,vector'
volumes: 
  postgres_data: